---
deployment:
  tasks:
    - export DEPLOYPATH=/home/scouti1q/
    - /bin/cp -r * $DEPLOYPATH/stampot/  #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/zozzycode.com/laradeploy/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/stampot_new.scouting-ijsselgroep.nl/js/
    - /bin/cp ./public/css/*.css $DEPLOYPATH/stampot_new.scouting-ijsselgroep.nl/css/
